config/routes.rb
Rails.application.routes.draw do
	root "projects#index"

  devise_for :users


  resources :projects do
  	resources :comments
  end

resources :users
resources :services
resources :tags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :project
	belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :comments
	has_many :taggings, as: :taggable
	has_many :tags, through: :taggings 

	#include Elasticsearch::Model
	#include Elasticsearch::Model::Callbacks

	#def self.search(params)
  	#	tire.search(load: true) do
    #		query { string params[:query], default_operator: "AND" } if params[:query].present?
    #		filter :range, published_at: {lte: Time.zone.now}
  	#	end
	#end


	def self.search(search)
  	  if search
        where("title like :q or description like :q", q: "%#{search}%")
      else
        Project.all
      end
	end

	def tag_list
	  self.tags.pluck(:name).join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  		self.tags = new_or_found_tags
	end

end

app/models/service.rb
class Service < ApplicationRecord
	belongs_to :user
	has_many :taggings, as: :taggable

	def self.search(search)
  	  if search
        where("title like :q or description like :q", q: "%#{search}%")
      else
        Service.all
      end
	end


	def tag_list
	  self.tags.collect do |tag|
	    tag.name
	  end.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  		self.tags = new_or_found_tags
	end
	
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tags
  belongs_to :taggable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
  has_many :comments
  has_many :services

  has_many :taggings, as: :taggable


  
  def self.search(search)
  	  if search
        where("title like :q or description like :q", q: "%#{search}%")
      else
        User.all
      end
	end


  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
      new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
      self.tags = new_or_found_tags
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def new
end


def create
  @comment = Comment.new(comment_params)
  @comment.project_id = params[:project_id]

  @comment.save

  redirect_to project_path(@comment.project)
end

def comment_params
  params.require(:comment).permit(:user, :body)
end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.search(params[:search]).page(params[:page]).per_page(10)
  end

  def show
    @project = Project.find(params[:id])
    @comment = Comment.new
    @comment.project_id = @project.id
    increment_counter(@project)
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.save
    redirect_to root_path
  end


  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
  end


  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:title, :price, :cashless, :description, :tag_list)
  end

  def increment_counter (project)
    project.watch_count = project.watch_count + 1
    project.save
  end


end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    @services = Service.search(params[:search]).page(params[:page]).per_page(10)
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    @service = Service.new
  end

  def edit
  end

  def create
    @service = Service.new(project_params)
    @service.save
  end


  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @service.destroy
  end


  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:service).permit(:name, :description, :price, :tag_list)
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	
	def index
		@tags=Tag.all
	end

  	def show
    	@tag = Tag.find(params[:id])
  	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.search(params[:search]).page(params[:page]).per_page(10)
  end


  def show
    @user = User.find(params[:id])
  end


  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to current_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: current_user }
      else
        format.html { render :edit }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end


 private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:description, :money, :city, :birthday, :tag_list)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>
<%= form_for [ @project, @comment ] do |f| %>
  <p>
    <%= f.label :user %><br/>
    <%= f.text_field :user %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "new project", new_project_path %>

app/views/comments/new.html.erb
<h1>New Project</h1>
<p id="notice"><%= notice %></p>
<%= render 'form', project: @project %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<h3>Comments</h3>
<%= render partial: 'projects/comment', collection: @project.comments %>

<%= link_to 'Edit', edit_project_path(@project) %> 

app/views/layouts/_footer.html.erb
   <footer>

          <p>Copyright &copy; Ilya Tsynenko 2016 </p>

    </footer> 

app/views/layouts/_header.html.erb
<div class=header>

    <% if user_signed_in? %>

      <li id="white_link"><%= link_to 'Account', edit_user_registration_path %></li>
      <li id="white_link"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li id="white_link"><%= link_to "Login", new_user_session_path, class: "active" %></li>
    <% end %>

</div>

app/views/layouts/_menu.html.erb
<table>
  <thead>
    <tr>
      <th>Categories</th>
    </tr>
  </thead>
  <tbody>
    <% Tag.all.each do |tag| %>
      <tr>
        <td><%= link_to tag.name, tag_path(tag) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freelansim</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class=container-fluid id="first-row">
    <div class=row>
       <div class=container>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "TM Feed", "http://tmfeed.ru" %></li>
            <li><%= link_to "Habrahabr", "https://habrahabr.ru" %></li>
            <li><%= link_to "Geektimes", "https://geektimes.ru" %></li>
            <li><%= link_to "Toster", "https://toster.ru" %></li>
            <li><%= link_to "Moy krug", "https://moikrug.ru" %></li>
          </div>
        </div>
    </div>
  </div>
  <div class=container-fluid id="second-row">
    <div class=row>
      <div class="navbar navbar-default">
      <div class=container>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li id="logo"><%= link_to "Freelansim", root_path %></li>
            <li><%= link_to "Projects", projects_path %></li>
            <li><%= link_to "Services", services_path %></li>
            <li><%= link_to "Freelancers", users_path %></li>
            <li><%= render 'layouts/header' %></li>
          </div>
        </div>
    </div>
  </div>
  <div class="container-fluid" id="main">
    <div class="row">
      <div class="col-lg-8" id="main-zone"><%= yield %></div>
      <div class="col-lg-4" id="right-menu"><%= render 'layouts/menu' %></div>
    </div>
  </div>
   
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/projects/_comment.html.erb
<div>
  <h4>Comment by <%= comment.user %></h4>
  <p>Posted <%= distance_of_time_in_words(comment.project.created_at, comment.created_at) %> later</p>
  <p class="comment"><%= comment.body %></p>
</div>

app/views/projects/_form.html.erb
<table>
  <%= simple_form_for @project do |f| %>
    <tr>
      <%= f.input :title %> <br />
    </tr>
    <tr>
      <%= f.input :price %><br />
      <%= f.input :cashless %>
    </tr>
    <tr>
      <%= f.input :description %><br />
    </tr>
    <tr>
      <%= f.input :tag_list %><br />
    </tr>
    <tr>
      <%= f.button :submit %>
    </tr>
  <% end %>
</table>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

Projects <%= @projects.count %>

<div id="search">
<%= form_tag projects_path, method: :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>
</div>


<div id="project">
<table>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <h2><%= link_to project.title, project %></h2>
        <p> <%= project.comments.count %> answers
        <%= project.watch_count %> watches 
        <%= distance_of_time_in_words(project.created_at, Time.now) %> ago
        <% if project.price %>
          <p><%= project.price %> rubles
        <% else %>
         <p> Contract price
        <% end %>
    <% project.tags do |tag| %>
      <tr>
        <td><%= link_to tag.name, tag_path(tag) %></td>
      </tr>
    <% end %>

      </tr>
      <hr>
    <% end %>
  </tbody>
</table>
</div>
  <div class="digg_pagination">
    <%= will_paginate @projects, :container => false, previous_label: "<", next_label: ">" %>
  </div>
<br>

<%= link_to "new project", new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<p id="notice"><%= notice %></p>
<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>
<p>
  Tags:
  <% @project.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<h3>Comments</h3>
<h3>Comments (<%= @project.comments.size %>)</h3>
<%= render partial: 'projects/comment', collection: @project.comments %>



<%= render partial: 'comments/form' %>


<%= link_to 'Edit', edit_project_path(@project) %> 

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
    <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form', service: @service %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<%= form_tag services_path, method: :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>


<table>
  <tbody>
    <% @services.each do |service| %>
      <tr>
        <h2><%= service.title %></h2>
        <%= link_to 'Show', service %>
      </tr>
      <% @service.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
      <% end %>
      </p>
    <% end %>
  </tbody>
</table>

  <div class="digg_pagination">
    <%= will_paginate @services, :container => false, previous_label: "<", next_label: ">" %>
  </div>
<br>

<%= link_to "new service", new_service_path %>

app/views/services/new.html.erb
<h1>New Service</h1>
<p id="notice"><%= notice %></p>
<%= render 'form', service: @service %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @service.name %>
</p>
<p>
  Tags:
  <% @service.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> 

app/views/tags/show.html.erb
<h1>Projects tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.projects.each do |project| %>
    <li><%= link_to project.title, project_path(project) %></li>
  <% end %>
</ul>


<h1>Services tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.services.each do |service| %>
    <li><%= link_to service.name, service_path(service) %></li>
  <% end %>
</ul>




<h1>Users tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.users.each do |user| %>
    <li><%= link_to user.name, user_path(user) %></li>
  <% end %>
</ul>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Freelancers</h1>

<%= form_tag users_path, method: :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>


<table>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <h2><%= link_to user.email, user %></h2>
          <% user.tags.each do |tag| %>
            <%= link_to tag.name, tag_path(tag) %>
          <% end %>
        <hr>
      </tr>
    <% end %>
  </tbody>
</table>
  <div class="digg_pagination">
    <%= will_paginate @users, :container => false, previous_label: "<", next_label: ">" %>
  </div>
<br>

<%= link_to "new user", new_user_path %>

app/views/users/show.html.erb
<h2><%= @user.email %></h2>

<p><%= @user.description %></p>
<p><%= @user.money %></p>
<p><%= @user.city %></p>
<p><%= @user.country %></p>
<p><%= @user.birthday %></p>
<p><%= @user.completed_projects %></p>